services:
  - type: web
    name: geo-lo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login.html
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: "1"
